### ISSUE TITLE
IMPORTANT - Go-mutesting is deleting everything

### ISSUE THREAD

**Issue by jamietanna** [avito-tech/go-mutesting#19] opened 2022-06-13 21:15 UTC
We should validate if https://github.com/zimmski/go-mutesting/issues/97  applies here too.

**Comment by thiagonache** [comment] 2022-06-20 11:42
@jamietanna yes. it does apply here too.

**Comment by thiagonache** [comment] 2022-06-20 12:12
FYI, I've found the root cause after some debugging. Turns out that I was deleting the temporary dir in two tests even using `t.Tempdir()` (crazyness). So the mutation was changing the temp dir to `./` and my own test was deleting the files.
I've fixed my code and nothing is deleted anymore. Sorry for the noise.

**Comment by jamietanna** [comment] 2022-06-20 12:14
Ah cool, so it was an issue with the implementation we were following, rather than the library?

Is there anything we may be able to do to make this library protect better against this, or happy to close the issues?

**Comment by thiagonache** [comment] 2022-06-20 12:15
>Ah cool, so it was an issue with the implementation we were following, rather than the library?

correct

>Is there anything we may be able to do to make this library protect better against this, or happy to close the issues?
happy to close the issue.

**Closed as completed** 2022-06-20 12:24 UTC

**Comment by xiegeo** [comment] 2023-01-16 03:42
Hi, this is a really cool project and thanks avito for maintaining it.

I want to piggyback off on this topic, since reading it has given me some thoughts on how to safely execute automated mutation tests.

The deletion of developer code is an indication of a wider problem, a mutated code base could do anything the developer account has access to. Most code bases are (hopefully) not one modification away from disaster, but this is not always guaranteed. For example, flipping a flag that turned connecting to the dev environment to production.

Are there any suggested mitigation technics or is the fear unfounded from experience? Would you use go-mutesting on an unfamiliar code base?
